---
stages:
  - build

build:fisica-particelle-atlas: &build_template
  image: docker:stable
  stage: build
  services:
    - docker:dind
  before_script:
    - docker info
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    CONTAINER_IMAGE: fisica-particelle-atlas
    REPOSITORY: airiopenlab
  script:
    - export QUAL_NAME=${REPOSITORY}/${CONTAINER_IMAGE}
    - mkdir -p $HOME/.docker
    - echo "$DOCKER_AUTH_CONFIG" > "$HOME/.docker/config.json"
    - docker pull $QUAL_NAME:latest || true
    - docker build --cache-from $QUAL_NAME:latest --tag $QUAL_NAME:$CI_BUILD_REF --tag $QUAL_NAME:latest ./${CONTAINER_IMAGE}/
    - docker push $QUAL_NAME:$CI_BUILD_REF
    - docker push $QUAL_NAME:latest
  only:
    - web

build:fisica-stato-solido: 
  <<: *build_template
  variables:
    CONTAINER_IMAGE: fisica-stato-solido
