stages:
- build

build:linux-gpu:
  stage: build
  tags:
    - docker
    - linux
  #before_script:
  #  - mkdir -p $HOME/.docker
  #  - echo "$DOCKER_AUTH_CONFIG" > "$HOME/.docker/config.json"
  script:
    - docker build -t ubuntu18-phys-root .
